name: publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: build
        uses: ./.github/actions/build

      - name: publish
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: apps/web/storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v5
